-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Jan 01, 2025 at 11:52 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `video_blog`
--

-- --------------------------------------------------------

--
-- Table structure for table `recipes`
--

CREATE TABLE `recipes` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `video_link` varchar(255) NOT NULL,
  `img` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `recipes`
--

INSERT INTO `recipes` (`id`, `title`, `description`, `video_link`, `img`) VALUES
(1, 'Fried Potatoes With Mushrooms', '<h2>Fried Potatoes with Mushrooms</h2>\r\n  <h3>Ingredients</h3>\r\n  <ul>\r\n    <li>4 medium potatoes, peeled and sliced</li>\r\n    <li>200–300g mushrooms, cleaned and sliced</li>\r\n    <li>1 medium onion, thinly sliced</li>\r\n    <li>2 garlic cloves, minced (optional)</li>\r\n    <li>2 tbsp butter (optional)</li>\r\n    <li>2–3 tbsp oil (vegetable or olive)</li>\r\n    <li>Salt, to taste</li>\r\n    <li>Black pepper, to taste</li>\r\n    <li>Fresh herbs (dill, parsley, or chives) for garnish</li>\r\n  </ul>\r\n  <h3>Instructions</h3>\r\n  <ol>\r\n    <li>Heat oil in a large skillet over medium heat.</li>\r\n    <li>Add the sliced potatoes, spread them evenly, and fry until golden on one side.</li>\r\n    <li>Flip the potatoes and add the sliced onions. Fry for another 5 minutes.</li>\r\n    <li>Add the mushrooms and garlic (if using). Stir occasionally and cook until mushrooms are tender.</li>\r\n    <li>Season with salt and black pepper to taste.</li>\r\n    <li>Optional: Add butter for extra flavor and stir well.</li>\r\n    <li>Garnish with fresh herbs before serving.</li>\r\n  </ol>', 'https://www.youtube.com/embed/heuImM1dzTc', 'Fried-Potatoes-With-Mushrooms.avif'),
(2, 'Greek Salad', '<h2>Greek Salad</h2>\r\n  <h3>Ingredients</h3>\r\n  <ul>\r\n    <li>2 large tomatoes, chopped</li>\r\n    <li>1 cucumber, sliced into half-moons</li>\r\n    <li>1 red onion, thinly sliced</li>\r\n    <li>1 green bell pepper, sliced</li>\r\n    <li>100g feta cheese, cubed or crumbled</li>\r\n    <li>1/2 cup Kalamata olives</li>\r\n    <li>3–4 tbsp olive oil</li>\r\n    <li>1 tbsp red wine vinegar</li>\r\n    <li>1 tsp dried oregano</li>\r\n    <li>Salt and black pepper, to taste</li>\r\n  </ul>\r\n  <h3>Instructions</h3>\r\n  <ol>\r\n    <li>In a large bowl, combine tomatoes, cucumber, red onion, and green bell pepper.</li>\r\n    <li>Add the Kalamata olives and feta cheese.</li>\r\n    <li>Drizzle with olive oil and red wine vinegar.</li>\r\n    <li>Sprinkle with dried oregano, salt, and black pepper to taste.</li>\r\n    <li>Toss gently to combine all ingredients.</li>\r\n    <li>Serve immediately or chill briefly before serving.</li>\r\n  </ol>', 'https://www.youtube.com/embed/Pc1OORZb57g?si=agYT3gSoSG_gpZa6', 'Greek-Salad.avif'),
(3, 'Perfect Beef Steak AAA', '<h2>Perfect Beef Steak AAA</h2>\r\n  <h3>Ingredients</h3>\r\n  <ul>\r\n    <li>1 AAA-grade beef steak (ribeye, sirloin, or tenderloin), about 1-inch thick</li>\r\n    <li>2 tbsp olive oil</li>\r\n    <li>2 cloves garlic, smashed</li>\r\n    <li>2 sprigs fresh rosemary or thyme</li>\r\n    <li>1 tbsp butter</li>\r\n    <li>Salt, to taste</li>\r\n    <li>Freshly ground black pepper, to taste</li>\r\n  </ul>\r\n  <h3>Instructions</h3>\r\n  <ol>\r\n    <li>Remove the steak from the fridge and let it come to room temperature (about 30 minutes).</li>\r\n    <li>Season the steak generously with salt and freshly ground black pepper on both sides.</li>\r\n    <li>Heat a skillet or cast-iron pan over high heat and add the olive oil.</li>\r\n    <li>Once the oil is hot, place the steak in the pan and sear for 2–3 minutes on one side until a golden crust forms.</li>\r\n    <li>Flip the steak, add butter, garlic, and rosemary/thyme to the pan.</li>\r\n    <li>While searing the other side, baste the steak by spooning the melted butter over it for about 2 minutes.</li>\r\n    <li>Remove the steak from the pan and let it rest for 5–7 minutes to allow juices to redistribute.</li>\r\n    <li>Slice and serve with your favorite side dishes.</li>\r\n  </ol>', 'https://www.youtube.com/embed/3dEEylRXG9c', 'Perfect-Beef-Steak-AAA.avif'),
(4, 'French Rabbit In The Oven', '<h2>French Rabbit in the Oven</h2>\r\n  <h3>Ingredients</h3>\r\n  <ul>\r\n    <li>1 whole rabbit, cut into pieces</li>\r\n    <li>2 tbsp olive oil</li>\r\n    <li>2 tbsp butter</li>\r\n    <li>1 onion, finely chopped</li>\r\n    <li>4 garlic cloves, minced</li>\r\n    <li>1 cup dry white wine</li>\r\n    <li>1 cup chicken or vegetable broth</li>\r\n    <li>2 sprigs fresh thyme</li>\r\n    <li>2 bay leaves</li>\r\n    <li>Salt and freshly ground black pepper, to taste</li>\r\n    <li>1/2 cup heavy cream (optional, for a creamy version)</li>\r\n  </ul>\r\n  <h3>Instructions</h3>\r\n  <ol>\r\n    <li>Preheat the oven to 180°C (350°F).</li>\r\n    <li>Season the rabbit pieces with salt and black pepper.</li>\r\n    <li>In a large oven-safe skillet or Dutch oven, heat olive oil and butter over medium-high heat.</li>\r\n    <li>Sear the rabbit pieces on all sides until golden brown, then remove and set aside.</li>\r\n    <li>In the same pan, sauté the onion and garlic until softened and fragrant.</li>\r\n    <li>Deglaze the pan with white wine, scraping up any browned bits, and let it reduce slightly.</li>\r\n    <li>Return the rabbit to the pan, add the broth, thyme, and bay leaves.</li>\r\n    <li>Cover the skillet with a lid or foil and place it in the oven.</li>\r\n    <li>Bake for 45–60 minutes, or until the rabbit is tender and fully cooked.</li>\r\n    <li>Optional: Stir in heavy cream during the last 10 minutes for a creamy sauce.</li>\r\n    <li>Remove from the oven, discard the thyme and bay leaves, and serve hot.</li>\r\n  </ol>', 'https://www.youtube.com/embed/u9sU43GnYrg?si=loY4SrdpceG1b6tl', 'French-Rabbit-In-The-Oven.avif'),
(5, 'Chicken Sandwich', '<h2>Vietnamese Chicken Sandwich (Bánh Mì Gà)</h2>\r\n  <h3>Ingredients</h3>\r\n  <ul>\r\n    <li>1 baguette (crusty, Vietnamese-style preferred)</li>\r\n    <li>1 cooked chicken breast, shredded or thinly sliced</li>\r\n    <li>1 small carrot, julienned</li>\r\n    <li>1/2 cucumber, thinly sliced</li>\r\n    <li>1/2 cup daikon radish, julienned (optional)</li>\r\n    <li>2 tbsp mayonnaise</li>\r\n    <li>1 tsp soy sauce</li>\r\n    <li>Fresh cilantro leaves</li>\r\n    <li>1 jalapeño or chili pepper, thinly sliced (optional)</li>\r\n    <li>1 tsp rice vinegar</li>\r\n    <li>1 tsp sugar</li>\r\n    <li>Salt, to taste</li>\r\n  </ul>\r\n  <h3>Instructions</h3>\r\n  <ol>\r\n    <li>In a small bowl, mix the carrot, daikon radish, rice vinegar, sugar, and a pinch of salt. Let it sit for 10 minutes to pickle slightly.</li>\r\n    <li>Toast the baguette until warm and crispy, then slice it lengthwise.</li>\r\n    <li>Spread mayonnaise on the inside of the baguette and drizzle with a little soy sauce.</li>\r\n    <li>Layer the shredded chicken, pickled carrot and radish, cucumber slices, and cilantro leaves.</li>\r\n    <li>Add jalapeño slices for extra spice, if desired.</li>\r\n    <li>Close the sandwich, press gently, and serve immediately.</li>\r\n  </ol>', 'https://www.youtube.com/embed/Wk1tKlgMheQ?si=S-5PLBBDwgeOhdXN', 'Chicken-Sandwich.avif'),
(6, 'Russian Borscht Soup', '<h2>Russian Borscht Soup</h2>\r\n  <h3>Ingredients</h3>\r\n  <ul>\r\n    <li>1 lb (450g) beef or pork (with bone, for broth)</li>\r\n    <li>6 cups water</li>\r\n    <li>2 medium beets, peeled and grated</li>\r\n    <li>2 medium potatoes, peeled and diced</li>\r\n    <li>1 carrot, peeled and grated</li>\r\n    <li>1 onion, finely chopped</li>\r\n    <li>1/4 head of cabbage, shredded</li>\r\n    <li>2 tbsp tomato paste</li>\r\n    <li>2 tbsp vegetable oil</li>\r\n    <li>2 cloves garlic, minced</li>\r\n    <li>1 tbsp vinegar (white or apple cider)</li>\r\n    <li>1 tbsp sugar</li>\r\n    <li>Salt and black pepper, to taste</li>\r\n    <li>Fresh dill or parsley, chopped (for garnish)</li>\r\n    <li>Sour cream (for serving)</li>\r\n  </ul>\r\n  <h3>Instructions</h3>\r\n  <ol>\r\n    <li>In a large pot, add the beef or pork and water. Bring to a boil, skim off the foam, reduce heat, and simmer for 1–1.5 hours to create a flavorful broth.</li>\r\n    <li>Remove the meat, shred it, and set aside. Strain the broth if needed and return it to the pot.</li>\r\n    <li>Heat vegetable oil in a skillet over medium heat. Sauté the grated beets for 3–4 minutes.</li>\r\n    <li>Add vinegar, sugar, and tomato paste to the beets. Stir well and cook for another 5 minutes. Set aside.</li>\r\n    <li>To the pot of broth, add diced potatoes and cook for 10 minutes.</li>\r\n    <li>Add the shredded cabbage, grated carrot, and chopped onion. Cook for another 10 minutes.</li>\r\n    <li>Stir in the sautéed beets and minced garlic. Season with salt and black pepper to taste.</li>\r\n    <li>Simmer the soup for 10–15 minutes until all vegetables are tender.</li>\r\n    <li>Return the shredded meat to the pot and let it warm through.</li>\r\n    <li>Serve hot, garnished with fresh dill or parsley and a dollop of sour cream.</li>\r\n  </ol>', 'https://www.youtube.com/embed/qRospcusjCE?si=19BoDACgnQhu_kqR', 'Russian-Borscht-Soup.avif');

-- --------------------------------------------------------

--
-- Table structure for table `stories`
--

CREATE TABLE `stories` (
  `id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `thumb` varchar(255) NOT NULL,
  `content` text NOT NULL,
  `imgs` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `stories`
--

INSERT INTO `stories` (`id`, `title`, `thumb`, `content`, `imgs`) VALUES
(1, 'Carbonara', 'assets/imgs/stories/1/thumb.jpg', '<p>\r\nEl Capitan stands tall beneath the sky,\r\nWith morning light that warms his rugged face;\r\nIn sturdy pan, the guanciale shall fry,\r\nA dance of crisp and sizzle fills the space.\r\n</p>\r\n<p>\r\nHe stirs the pasta, golden strands take flight,\r\nWhile eggs and cheese are whisked into a cream;\r\nThe crack of blackened pepper in the light,\r\nCompletes his vision, more than just a dream.\r\n</p>\r\n<p>\r\nHe merges all, the pan\'s heat lends embrace,\r\nNo cream in sight—tradition holds its ground;\r\nThe sauce, like silk, entwines with tender grace,\r\nAs laughter echoes, joy and love profound.\r\n</p>\r\n<p>\r\nEl Capitan, with every bite, we cheer,\r\nHis Carbonara sings—a taste sincere.\r\n</p>', 'assets/imgs/stories/1/1.jpg,assets/imgs/stories/1/2.jpg'),
(2, 'Morning Serenade', 'assets/imgs/stories/2/thumb.jpg', '<p>At dawn he wakes, the sea still in his veins,\r\nThe Capitan, with care, begins his art.\r\nHe wields his pan as if it held the reins,\r\nCreating meals to stir his lover\'s heart.</p>\r\n\r\n<p>The eggs he poaches soft, their centers gold,\r\nWith ribbons of warm sauce, they gently shine.\r\nUpon the ham, their creamy folds take hold,\r\nAnd cherry tomes with dew are placed in line.</p>\r\n\r\n<p>A steaming cup of tea, a lemon’s zest,\r\nCompletes the tray he carries to her side.\r\nHer sleepy smile confirms he’s passed the test,\r\nFor in his work, his love cannot be denied.</p>\r\n\r\n<p>Oh, Capitan, your heart and hands align,\r\nTo craft a feast where love and taste combine.</p>', 'assets/imgs/stories/2/1.jpg,assets/imgs/stories/2/2.jpg'),
(3, 'The Escargot', 'assets/imgs/stories/3/thumb.jpg', '<p>\r\n    Beneath the midday sun, El Capitan\r\nPrepared his feast with care and steady hand.\r\nThe escargot, a treasure of the land,\r\nMet batter light as silk, by skillful plan.\r\n</p>\r\n\r\n<p>\r\n    He whisked the golden mix with rhythmic flair,\r\nA gentle dance of spices, flour, and cream.\r\nThe shells, their hidden jewels beyond compare,\r\nAwaited glory in the rising steam.\r\n</p>\r\n\r\n<p>\r\n    The sizzling pan sang songs of thyme and heat,\r\nAs butter kissed each morsel, rich and pure.\r\nA sailor’s art, transforming life\'s retreat\r\nInto a dish no palate could endure.\r\n</p>\r\n\r\n<p>\r\n    Thus, from his hands, a masterpiece took flight—\r\nA meal to crown the splendor of the night.\r\n</p>', 'assets/imgs/stories/3/1.jpg'),
(4, 'Asian style noodle soup with beef', 'assets/imgs/stories/4/thumb.jpg', '<p>Beneath the sun, where ocean waves break free,\r\nEl Capitan stands tall with calm and might,\r\nPrepares a feast of noodles by the sea,\r\nA broth of speed and savory delight.</p>\r\n\r\n<p>With deft, quick hands he slices tender beef,\r\nBoiled eggs are halved and gleam in golden glow,\r\nAnd ginger’s warmth brings spice beyond belief,\r\nWhile soy and broth unite in fragrant flow.</p>\r\n\r\n<p>The noodles swirl, entwined in smoky steam,\r\nGreen onions sprinkled like the morning dew,\r\nHe ladles bowls, a sailor\'s fleeting dream,\r\nA soup that’s swift, yet deep in flavor true.</p>\r\n\r\n<p>On deck they savor, basked in sunlit gleam,\r\nEl Capitan\'s creation, pure as a dream.</p>', 'assets/imgs/stories/4/1.jpg,assets/imgs/stories/4/2.jpg'),
(5, 'Tankini Duck With Rice', 'assets/imgs/stories/5/thumb.jpg', '<p>El Capitan, at dawn\'s first light,\r\nPrepares his dish with skill and grace,\r\nA tankini duck, cooked golden bright,\r\nWith rice to fill its rightful place.</p>\r\n\r\n<p>Beside, the broccoli, fresh and green,\r\nMushrooms and carrots join the play,\r\nAll tossed and turned in wok’s sheen,\r\nA vibrant mix to greet the day.</p>\r\n\r\n<p>With every stir, the flavors blend,\r\nEach spice and herb a joyful sound,\r\nAs vegetables and duck commend\r\nThe feast that soon shall all astound.</p>\r\n\r\n<p>El Capitan, his task complete,\r\nServes up a meal both bold and sweet.</p>', 'assets/imgs/stories/5/1.jpg '),
(6, 'Beefsteak With Chickpeas Salad', 'assets/imgs/stories/6/thumb.jpg', '<p>El Capitan begins his midday art,\r\nWith steak in hand, his steady gaze alight.\r\nHe sears the fillet, each side set apart,\r\nUntil it browns beneath the fire’s bite.</p>\r\n\r\n<p>A dash of salt, some pepper to enhance,\r\nAs oils and juices blend in tender heat.\r\nHe turns the meat with graceful, practiced stance,\r\nCreating flavors bold and strong yet sweet.</p>\r\n\r\n<p>Beside, a bowl of chickpeas rests nearby,\r\nMixed with red onion, cypress leaves laid bare.\r\nOlive oil flows, balsamic’s depth runs high,\r\nA simple blend, refined with mindful care.</p>\r\n\r\n<p>With pride, he plates—each taste and texture clear,\r\nA humble feast to nourish all who’re near.</p>', 'assets/imgs/stories/5/1.jpg'),
(7, 'Patate Al Forno', 'assets/imgs/stories/7/thumb.jpg', '<p>Patate al Forno, golden, crisp, and bright,\r\nBegin the feast with fragrant herbs in tow.\r\nEl Capitan, by midday’s warming light,\r\nAttends each slice as olive oils flow.</p>\r\n\r\n<p>With garlic cloves and rosemary to blend,\r\nHe roasts until the edges brown and curl.\r\nEach bite, a mix of earth and sea’s commend,\r\nThe humble spud transformed, its flavors swirl.</p>\r\n\r\n<p>Then comes the salmon, set to sizzle low,\r\nIts skin a crisp, its flesh a tender pink.\r\nTogether, side by side, their warmth to show,\r\nA feast of taste and scent, in midday’s blink.</p>\r\n\r\n<p>So Capitan delights in simple fare,\r\nHis midday meal a craft beyond compare.</p>', 'assets/imgs/stories/7/1.jpg'),
(8, 'Fried Salmon On Rice', 'assets/imgs/stories/8/thumb.jpg', '<p>Upon the flame, El Capitan does stand,\r\nWith salmon fillets sizzling in his pan,\r\nTheir golden edges kissed by seasoned hand,\r\nA feast begun, according to his plan.</p>\r\n\r\n<p>The fragrant rice steams soft beside the heat,\r\nIts grains absorbing spices from the air,\r\nA pairing rich, both simple and complete,\r\nCrafted with utmost skill and tender care.</p>\r\n\r\n<p>He turns the fish, its skin crisped to perfection,\r\nA splash of oil sends waves of scent to rise.\r\nThe kitchen hums with flavors of affection,\r\nA master’s dish beneath the starry skies.</p>\r\n\r\n<p>El Capitan, with grace and skill so fine,\r\nTransforms his humble meal to one divine.</p>', 'assets/imgs/stories/8/1.jpg'),
(9, 'El Capitan’s Gnocchi ai Funghi', 'assets/imgs/stories/9/thumb.jpg', '<p>El Capitan, with hands both skilled and true,\r\nRolls out the gnocchi, smooth as morning light,\r\nHe shapes each piece, with patience, not askew,\r\nA simple craft turned into pure delight.</p>\r\n\r\n<p>In olive oil, the garlic starts to sing,\r\nAs mushrooms join, their scent a rich perfume,\r\nWith wine and herbs, they dance, they twist, they cling,\r\nAnd fill the pan with flavors that consume.</p>\r\n\r\n<p>The gnocchi simmer, tender in their prime,\r\nThen tossed with butter, cream, and touch of sage,\r\nHe lifts the dish, a masterpiece in time,\r\nA taste that speaks of more than just the age.</p>\r\n\r\n<p>So take a bite, and let your senses know,\r\nThe warmth of Italy in every glow.</p>', 'assets/imgs/stories/9/1.jpg,assets/imgs/stories/9/2.jpg'),
(10, 'The Pollo Paillard', 'assets/imgs/stories/10/thumb.jpg', '<p>El Capitan stands tall, his stance so sure,\r\nWith knife in hand, he tends to chicken\'s flesh.\r\nUpon the board, the fillets rest, so pure,\r\nAs he prepares his dish, each stroke is fresh.</p>\r\n\r\n<p>With practiced grace, he pounds the meat so thin,\r\nCreating perfect cuts with tender care.\r\nA sprinkle here, a dash of spice within,\r\nHe crafts with art, each flavor rich and rare.</p>\r\n\r\n<p>The pan is hot, the butter starts to melt,\r\nA golden crust forms crisp beneath the flame.\r\nHe flips with ease, as if the heat were felt\r\nBy none but him, his passion like a claim.</p>\r\n\r\n<p>The Pollo Paillard, a feast of simple grace,\r\nEl Capitan\'s art, with love and skill embraced.</p>', 'assets/imgs/stories/10/1.jpg'),
(11, 'Tuscan butter salmon with tortellini', 'assets/imgs/stories/11/thumb.jpg', '<p>Beneath El Capitan\'s majestic gaze,\r\nA chef prepares a feast of grand delight,\r\nWith Tuscan butter in the fire\'s blaze,\r\nHe crafts a meal to match the mountain\'s height.</p>\r\n\r\n<p>The salmon sears with herbs and garlic\'s kiss,\r\nIts tender flesh a masterpiece in gold,\r\nWhile tortellini, soft in buttery bliss,\r\nDance in the pan as stories old unfold.</p>\r\n\r\n<p>Each bite a journey through the Tuscan hills,\r\nWhere vineyards stretch beneath the sun\'s embrace,\r\nAnd every flavor in the dish fulfills\r\nA taste of Italy in nature\'s grace.</p>\r\n\r\n<p>El Capitan looks on, both proud and still,\r\nAs man and mountain share this perfect thrill.</p>', 'assets/imgs/stories/11/1.jpg,assets/imgs/stories/11/2.jpg'),
(12, 'Quail With Mashed Potato', 'assets/imgs/stories/12/thumb.jpg', '<p>Beneath the towering cliffs of granite stone,\r\nEl Capitan, in evening’s gentle glow,\r\nPrepares the quail, its secrets all his own,\r\nTo roast within the oven\'s steady flow.</p>\r\n\r\n<p>He brushes olive oil with patient grace,\r\nAnd sprinkles basilic, a touch divine,\r\nThen slides the quail into its warm embrace,\r\nWhere heat will turn the flesh to tender wine.</p>\r\n\r\n<p>The oven hums, a steady, soothing sound,\r\nAs quail transforms within its heated womb,\r\nNo flame is needed, no great fire around,\r\nJust even warmth to guide it to its bloom.</p>\r\n\r\n<p>Beneath the stars, the mountain rests in peace,\r\nAs El Capitan serves his masterpiece.</p>', 'assets/imgs/stories/12/1.jpg'),
(13, 'Fried Dumplings', 'assets/imgs/stories/13/thumb.jpg', '<p>El Capitan, a traveler bold and free,\r\nSet sail for China’s distant, ancient lands,\r\nWhere rivers flow and forests whisper, see,\r\nThe temples rising where the green expands.</p>\r\n\r\n<p>In markets bustling with life’s vibrant beat,\r\nHe wandered, tasting all the land\'s delights,\r\nFrom fragrant teas to dishes rich and sweet,\r\nAnd lanterns glowing softly in the night.</p>\r\n\r\n<p>Inspired by the flavors he did find,\r\nHe learned the art of dumplings from a sage,\r\nWith vegetables and spices well combined,\r\nHe mastered recipes of every age.</p>\r\n\r\n<p>El Capitan, with wisdom in his hand,\r\nReturned to share the tastes of China\'s land.</p>', 'assets/imgs/stories/13/1.jpg'),
(14, 'Rognon à la moutarde', 'assets/imgs/stories/14/thumb.jpg', '<p>Through Paris streets, El Capitan once roved,\r\nA culinary master of the arts.\r\nWith chef’s resolve, his craft he deftly proved,\r\nCreating dishes that delight the hearts.</p>\r\n\r\n<p>From markets fresh, he gathered champignons,\r\nAnd mustard seeds to blend with veal so fine.\r\nA secret sauce, a Parisian anon,\r\nEnhances flavors, rich like vintage wine.</p>\r\n\r\n<p>Rognon à la moutarde, a bold delight,\r\nA triumph in the city’s bustling grace.\r\nEl Capitan, beneath the city lights,\r\nBrings Paris charm to every warm embrace.</p>\r\n\r\n<p>A master’s touch in kitchens far and near,\r\nA French cuisine, with soul and skill sincere.</p>', 'assets/imgs/stories/14/1.jpg'),
(15, 'Fried Rice With Chicken', 'assets/imgs/stories/15/thumb.jpg', '<p>In days of old when sailors ruled the seas,\r\nEl Capitan, with pan and wok in hand,\r\nDid stir the rice with skill and perfect ease,\r\nCreating dishes legendary, grand.</p>\r\n\r\n<p>His fried rice, Asian style, a seafaring delight,\r\nWith soy and spices dancing in the breeze,\r\nBrought joy to all who tasted every bite,\r\nA culinary wonder sure to please.</p>\r\n\r\n<p>The crew would gather \'round with eager eyes,\r\nTo watch him cook, their tummies filled with cheer,\r\nHe’d toss and flip, beneath the starry skies,\r\nTheir laughter mixing with the night’s cool air.</p>\r\n\r\n<p>El Capitan, the master of the sea,\r\nAnd fried rice king, for all eternity.</p>', 'assets/imgs/stories/15/1.jpg'),
(16, 'Grilled Salmon', 'assets/imgs/stories/16/thumb.jpg', '<p>Upon the grill, with sizzle, flame, and cheer,\r\nLays salmon pink, a fish both grand and bright.\r\nEl Capitan, the cook we hold so dear,\r\nPrepares his feast beneath the stars\' soft light.</p>\r\n\r\n<p>With spatula in hand, he flips with flair,\r\nA chef renowned, with hat perched high and proud.\r\nThe salmon dances, golden in the air,\r\nIts flavor sings, delightful, clear, and loud.</p>\r\n\r\n<p>\"Taste the sea!\" he cries with jovial tone,\r\nAs diners cheer and clap, a hungry throng.\r\nWith every bite, their joy is deeply sown,\r\nEl Capitan, the king of grill and song.</p>\r\n\r\n<p>So here’s to salmon, cooked with love and thrill,\r\nAnd to our captain, master of the grill.</p>', 'assets/imgs/stories/16/1.jpg'),
(17, 'Portuguese Octopus', 'assets/imgs/stories/17/thumb.jpg', '<p>In the kitchen, bright and clean,\r\nAn octopus with limbs both deft and sly,\r\nDreamed of adventures far beyond cuisine,\r\nYet found himself where sea meets pan and fry.</p>\r\n\r\n<p>He danced with garlic, butter, lemon zest,\r\nAvoiding pots and pans with crafty ease.\r\nEl Capitan, the chef, aimed for the best,\r\nBut octopus, with humor, sought to tease.</p>\r\n\r\n<p>\"Oh fate!\" he cried, \"to be a gourmet treat,\r\nWhen I could swim through coral reefs so wide.\r\nInstead, I\'m here, where hot and cold compete,\r\nMy destiny to serve, yet still with pride.\"</p>\r\n\r\n<p>In El Capitan\'s domain, he played his part,\r\nA culinary jest, a chef\'s fine art.</p>', 'assets/imgs/stories/17/1.jpg,assets/imgs/stories/17/2.jpg'),
(18, 'Naked Lobster ', 'assets/imgs/stories/18/thumb.jpg', '<p>Upon the deck where salty breezes blow,\r\nEl Capitan commands with eyes so keen,\r\nA master of the sea where currents flow,\r\nAnd of the kitchen, where his craft is seen.</p>\r\n\r\n<p>With steady hand, he carves the ocean\'s prize,\r\nA lobster, fresh and bright from morning\'s catch,\r\nEach movement sure, beneath the azure skies,\r\nHe works with grace, no challenge left to match.</p>\r\n\r\n<p>In butter\'s golden pool, his dish takes flight,\r\nWith garlic\'s fragrant kiss, a touch of lime,\r\nHe conjures flavors, simple yet so bright,\r\nTransforming meals into a taste sublime.</p>\r\n\r\n<p>El Capitan, of sea and stove the king,\r\nIn every dish, his passion\'s song does sing.</p>', 'assets/imgs/stories/18/1.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `recipes`
--
ALTER TABLE `recipes`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `stories`
--
ALTER TABLE `stories`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `recipes`
--
ALTER TABLE `recipes`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `stories`
--
ALTER TABLE `stories`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=19;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
